# The main configuration file

# All the env variables are duplicated here into toml keys to allow the app to use a unified api for
# accessing the config

[main]
name = 'ASK API'
version = '1.0.0'

# Migration folder Name
# Note: This must be valid python identifier name
# Example: 'master' or 'new_feature'
migration_folder_name = 'main'

secret_key = "$APP_SECRET_KEY"

[runtime]
debug = "$APP_DEBUG"
